# -*- mode: python ; coding: utf-8 -*-


a = Analysis(
    ['Athey_Deck.py'], 
    pathex=[],
    binaries=[],
    datas=[('hidapi.dll', '.'), ('img\\Logo.png', '.'), ('img\\streamdeck_key1.png', '.'), ('img\\streamdeck_key2.png', '.'), ('img\\streamdeck_key3.png', '.'), 
    ('img\\streamdeck_key1-alert.png', '.'), ('img\\streamdeck_key2-alert.png', '.'), ('img\\streamdeck_key3-alert.png', '.'), ('img\\streamdeck_key4.png', '.'), 
    ('img\\streamdeck_key4-alert.png', '.'), ('img\\streamdeck_key5.png', '.'), ('img\\streamdeck_key5-alert.png', '.'), ('img\\TEST2_Alert.png', '.'), 
    ('img\\LPR_Alert-Yellow.png', '.'), ('img\\LPR_Alert-Orange.png', '.'), ('img\\LPR_Alert-Red.png', '.'), ('img\\POI_Alert-Yellow.png', '.'), 
    ('img\\POI_Alert-Orange.png', '.'), ('img\\POI_Alert-Red.png', '.'), ('img\\Alerts-Disabled.png', '.'), ('img\\streamdeck_key1-brett.png', '.'), 
    ('img\\streamdeck_key2-brett.png', '.'), ('img\\streamdeck_key3-brett.png', '.'), ('img\\streamdeck_key4-brett.png', '.'), 
    ('img\\streamdeck_key5-brett.png', '.'), ('img\\Brett-Alert.png', '.'), ('img\\tom_hanks_2.png', '.'), ('img\\alert-button.png', '.'),
    ('img\\streamdeck_key1-yellow.png', '.'), ('img\\streamdeck_key2-yellow.png', '.'), ('img\\streamdeck_key3-yellow.png', '.'), 
    ('img\\streamdeck_key4-yellow.png', '.'), ('img\\streamdeck_key5-yellow.png', '.'), ('img\\streamdeck_key1-orange.png', '.'), 
    ('img\\streamdeck_key2-orange.png', '.'), ('img\\streamdeck_key3-orange.png', '.'), ('img\\streamdeck_key4-orange.png', '.'), 
    ('img\\streamdeck_key5-orange.png', '.'), ('img\\streamdeck_brett-blank.png', '.'), ('img\\streamdeck_yellow-blank.png', '.'), 
    ('img\\streamdeck_orange-blank.png', '.'), ('img\\streamdeck_red-blank.png', '.'), ('img\\streamdeck_key6.png', '.'), ('img\\streamdeck_key6-alert.png', '.'), 
    ('img\\streamdeck_key6-brett.png', '.'), ('img\\streamdeck_key6-orange.png', '.'), ('img\\streamdeck_key6-yellow.png', '.'), ('img\\streamdeck_key7.png', '.'), 
    ('img\\streamdeck_key7-alert.png', '.'), ('img\\streamdeck_key7-brett.png', '.'), ('img\\streamdeck_key7-orange.png', '.'), ('img\\streamdeck_key7-yellow.png', '.'), 
    ('img\\streamdeck_ad1.png', '.'), ('img\\streamdeck_ad1-alert.png', '.'), ('img\\streamdeck_ad1-brett.png', '.'), ('img\\streamdeck_ad1-yellow.png', '.'), 
    ('img\\streamdeck_ad1-orange.png', '.'), ('img\\streamdeck_ad2.png', '.'), ('img\\streamdeck_ad2-alert.png', '.'), ('img\\streamdeck_ad2-brett.png', '.'), 
    ('img\\streamdeck_ad2-yellow.png', '.'), ('img\\streamdeck_ad2-orange.png', '.'), ('img\\streamdeck_key1-blue.png', '.'), ('img\\streamdeck_key2-blue.png', '.'), 
    ('img\\streamdeck_key3-blue.png', '.'), ('img\\streamdeck_key4-blue.png', '.'), ('img\\streamdeck_key5-blue.png', '.'), ('img\\streamdeck_key6-blue.png', '.'), 
    ('img\\streamdeck_key7-blue.png', '.'), ('img\\streamdeck_ad1-blue.png', '.'), ('img\\streamdeck_ad2-blue.png', '.'), ('img\\alert-button-press.png', '.'), 
    ('dist\\license_plates.txt', '.')],
    hiddenimports=[],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='Athey Deck',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=['img\\Logo.png'],
)
